### ISSUE TITLE
Regras de negócios

### ISSUE THREAD

**Issue by andreqbs** [andreqbs/e-star#1]
Regras do negócio são políticas, condições ou restrições que devem ser consideradas na execução dos processos existentes em uma organização.

**Comment by andreqbs** [comment]
![exemplo.jpg](https://zube.io/files/andreqbs/1e51fd0f1a8e09142d32cb30becb2781.jpeg)

**Comment by claudiospaiva** [comment]
Prezado Professor, mediante discussão com a turma hoje, gostaria de pedir, em nome de todos, o adiamento da entrega do trabalho para a sexta-feira, dia 12/08, pois não temos aula quinta e sexta o que permitirá mais tempo para uma melhor elaboração dos trabalhos. Além disso, os poucos que já iniciaram sua facção estão tendo algumas dificuldades. Eu mesmo iniciei mas, pelo que percebi, se for para incluir todas as regras de "funcionamento" (negócio) do sistema de acordo com o edital, os documentos fornecidos e mais o recurso de padronização (abnt), requer mais tempo para sua elaboração. 

Att,
Claudio S. Paiva
Mat: 201401988

**Comment by domingosliraneto** [comment]
Boa noite colaboradores, como proposto em sala de aula, estou postando em anexo a minha proposta de negócios. A mesma encontra-se mo padrão disponibilizado pelo professor. Quero pedir a todos que leiam, e opinem sobre cada item elaborado, de certa forma, teremos que ler as propostas de todos e discuti-las, dessa forma conseguiremos entrar em um consenso e definir os pontos mais importantes de cada proposta. Posteriormente, necessitaremos que a equipe de Front-end/Designer, inicializem o mais rápido possível o desenvolvimentos das telas, para que a equipe de desenvolvedores  Back-end, possa codifica-las.
OBS: Professor, precisamos definir as equipes o quanto antes, as ideias estão surgindo a medida que leio os editais, pelo que vi não é algo tão simples, contem muitas regras que pode complicar o andajar do desenvolvimento.

Att, 
Domingos L.A. Neto
Setor de Desenvolvimento, Back-End.
[Documento de Requisitos de Negócio.pdf](https://github.com/andreqbs/e-star/files/414426/Documento.de.Requisitos.de.Negocio.pdf)

**Comment by JFhenrique** [comment]
Boa noite a todos, segue os Requisitos de negócios solicitado em sala de aula.
Obrigado pela atenção!

Att,
Jefferson Henrique Sousa Galvão

[Documento de Requisitos do Negócio.docx](https://github.com/andreqbs/e-star/files/416349/Documento.de.Requisitos.do.Negocio.docx)

**Comment by DerikSoares** [comment]
Segue ai também  os requisitos da regra de negócios solicitado na ultima aula
[Documento de Requisitos do Negócio 2.docx](https://github.com/andreqbs/e-star/files/416360/Documento.de.Requisitos.do.Negocio.2.docx)

**Comment by lidioleite** [comment]
Boa noite, Professor. 

Segue em anexo as regras de negócios conforme solicitado na ultima aula, não sei se fiz realmente o que foi solicitado, caso contrário gostaria de cor
[Regras de Negocios.docx](https://github.com/andreqbs/e-star/files/416369/Regras.de.Negocios.docx)
rigir em sala para que assim possa melhorar.

**Comment by lidioleite** [comment]
Boa noite, Professor.

Segue em anexo as regras de negócios conforme solicitado na ultima aula, não sei se fiz realmente o que foi solicitado, caso contrário gostaria de corrigir em sala para que assim possa melhorar.
[Regras de Negocios.docx](https://github.com/andreqbs/e-star/files/416371/Regras.de.Negocios.docx)

**Comment by claudiospaiva** [comment]
Mesmo já tendo enviado por email, postando aqui agora!
[Documento de Requisitos do Negócio_CSP.docx](https://github.com/andreqbs/e-star/files/416372/Documento.de.Requisitos.do.Negocio_CSP.docx)

**Comment by Elizabetearaujo** [comment]
Regras de negócios Elizabete
[Documento de Requisitos do Negócio mod.pdf](https://github.com/andreqbs/e-star/files/419153/Documento.de.Requisitos.do.Negocio.mod.pdf)

**Comment by WelltonQ** [comment]
Regras de Negócios - Wellton
[Trabalho 1.pdf](https://github.com/andreqbs/e-star/files/419191/Trabalho.1.pdf)
