### ISSUE TITLE
Diagrama de Classes

### ISSUE THREAD

**Issue by claudiospaiva** [andreqbs/e-star#15]

**Comment by claudiospaiva** [comment]
Segue anexo a versão beta do meu diagrama de classes.
[Class_Diagram--ByClaudio_Paiva_BetaVersion.zip](https://github.com/andreqbs/e-star/files/489905/Class_Diagram--ByClaudio_Paiva_BetaVersion.zip)

**Comment by lidioleite** [comment]
Boa tarde!

Segue anexo , o diagrama de classes para o projeto, conforme solicitado.

![DiagramaDeClassesTCC.jpg](https://zube.io/files/andreqbs/974e9a8d23c22cfb884121cb1b9ded6e.jpeg)

**Comment by lidioleite** [comment]
Boa Tarde,
Segue anexo o diagrama de classes, para o projeto E-start.

Atenciosamente,
Lídio Sales Leite
[DiagramaDeClasses.docx](https://github.com/andreqbs/e-star/files/491898/DiagramaDeClasses.docx)

**Comment by Elizabetearaujo** [comment]
Boa noite
Considerar este documento realizado pelo grupo da documentação.

[Mod_Conceitual UML Class Diagram.zip](https://github.com/andreqbs/e-star/files/491910/Mod_Conceitual.UML.Class.Diagram.zip)

**Comment by DerikSoares** [comment]
[DerikDiagrama.zip](https://github.com/andreqbs/e-star/files/491977/DerikDiagrama.zip)

**Comment by domingosliraneto** [comment]
Boa Noite, segue em anexo meu diagrama de casos de uso:
[domingos.zip](https://github.com/andreqbs/e-star/files/491999/domingos.zip)

**Comment by elisonmateus** [comment]
Boa noite


[Class Diagram.zip](https://github.com/andreqbs/e-star/files/492015/Class.Diagram.zip)

**Comment by WelltonQ** [comment]
Boa Noite, segue em anexo o Diagrama de Classes:

[Class Diagram (Wellton Quirino Alves da Silva).zip](https://github.com/andreqbs/e-star/files/492014/Class.Diagram.Wellton.Quirino.Alves.da.Silva.zip)

**Comment by claudiospaiva** [comment]
Segue o novo diagrama.
[ClassDiagram2_ByClaudioPaiva.zip](https://github.com/andreqbs/e-star/files/492018/ClassDiagram2_ByClaudioPaiva.zip)

**Comment by JFhenrique** [comment]
Boa Noite, segue em anexo o Diagrama de Classes:
[Class Diagram(Jefferson Henrique).pdf](https://github.com/andreqbs/e-star/files/492106/Class.Diagram.Jefferson.Henrique.pdf)

**Comment by andreqbs** [comment]
Diagrama de classes. Acredito que nessa primeira parte, vamos ter apenas um controlador que fará todas as ações. O diagrama não está completo, mas diria que tem 95% do que vamos usar.

Pessoal de programação, vamos trabalhar em cima disso.
Pessoal de banco de dados, mostrar na próxima aula as procedures de inserção, deletar e atualização de todas as tabelas do banco.
Pessoal de interface, já mostrar como será a tela de abertura após o cadastro, telas de cadastro de tcc, tela de inserção de notas e comentários do TCC1, tela de inserção de notas e comentários de banca de defesa (Basta olhar o PDF com os formulários que estão em anexo)

![e-start](https://cloud.githubusercontent.com/assets/7348964/19167989/6e659214-8be4-11e6-9090-da14543da51f.png)
