### ISSUE TITLE
Grupo : Documentação

### ISSUE THREAD

**Issue by andreqbs** [andreqbs/e-star#18]
- Construir no Astah o diagrama de classes disponibilizado por mim na tarefa (Diagrama de Classes)
- Realizar o diagrama de sequência de cadastro de um TCC e alteração de um TCC.
- Revisar o documento de casos de uso e o diagrama de casos de uso.
- Revisar o documento de regras de negócios.

Importante : A aluna Elizabeth está responsável pela delegação e cobrança das atividades no grupo de Documentação.

**Comment by marvan123** [comment]
![Screenshot_1.png](https://zube.io/files/andreqbs/9963c32b5c177a3b7c3a0fed1db2922d.png)

**Comment by Artur1520** [comment]
Boa noite, André.
Conversando com o pessoal da programação.
Surgiu uma duvida. No banco de dados tem uma entidade chamada atividades
O que exatamente seria isso ?

Fico no aguardo.

**Comment by Artur1520** [comment]
Boa noite, Professor.
Segue a regra de negócios atualizadas realizada junto com o pessoal da programação.
Link: https://docs.google.com/spreadsheets/d/1ggp_0OHQA29y5diZutYDl5Vpud6CkFfswwxdXk6OAC0/edit#gid=0

Atenciosamente
Artur Ewerton
