### ISSUE TITLE
Modelo de Casos de Uso

### ISSUE THREAD

**Issue by andreqbs** [andreqbs/e-star#2]

**Comment by Elizabetearaujo** [comment]
Regras de negocio
[Documento de Requisitos do Negócio mod.pdf](https://github.com/andreqbs/e-star/files/419082/Documento.de.Requisitos.do.Negocio.mod.pdf)

**Comment by andreqbs** [comment]
EXEMPLO DE MODELO

<img width="642" alt="captura de tela 2016-08-16 as 17 59 49" src="https://cloud.githubusercontent.com/assets/7348964/17715669/993478d8-63db-11e6-9428-2156e2df0f91.png">

**Comment by domingosliraneto** [comment]
Como solicitado, segue em anexo o Modelo de Casos de Uso.

[Diagrama de Casos de Uso 1.0.pdf](https://github.com/andreqbs/e-star/files/441521/Diagrama.de.Casos.de.Uso.1.0.pdf)
Att,
Domingos L.A. Neto
Setor de Desenvolvimento, Back-End.

**Comment by domingosliraneto** [comment]
Segue em anexo

**Comment by domingosliraneto** [comment]
Conforme solicitado, segue em anexo o Modelo de Casos de Uso.

Att,
Domingos L.A. Neto
Setor de Desenvolvimento, Back-End.
[Modelo de Casos de Uso.pdf](https://github.com/andreqbs/e-star/files/441529/Modelo.de.Casos.de.Uso.pdf)

**Comment by claudiospaiva** [comment]
Segue anexo o Modelo de Casos de Uso.
[Casos_de_Uso-BY_CSP.xlsx](https://github.com/andreqbs/e-star/files/443632/Casos_de_Uso-BY_CSP.xlsx)

**Comment by DerikSoares** [comment]
Segue o anexo dos trablhos solicitados
![diagrama](https://cloud.githubusercontent.com/assets/12520860/18072426/8da4b362-6e34-11e6-9ec4-c104b7e1dbcd.jpg)
[Sistema de cadastro de usuario para TCC.docx](https://github.com/andreqbs/e-star/files/443775/Sistema.de.cadastro.de.usuario.para.TCC.docx)

**Comment by lidioleite** [comment]
Olá professor, conforme solicitado estou enviando o meu modelo de casos de uso.
[Modelo de casos de uso.docx](https://github.com/andreqbs/e-star/files/443780/Modelo.de.casos.de.uso.docx)

**Comment by claudiospaiva** [comment]
Derik, vc fechou a tarefa, reabra Rs

**Comment by claudiospaiva** [comment]
consegui! Rs

**Comment by DerikSoares** [comment]
Desculpa ai claudio

**Comment by lidioleite** [comment]
Segue em anexo o diagrama de casos de uso, conforme solicitado! 
[Diagrama de casos de uso.docx](https://github.com/andreqbs/e-star/files/443834/Diagrama.de.casos.de.uso.docx)

**Comment by Elizabetearaujo** [comment]
Segue em anexo documento de casos de uso.
[Documento de caso de uso.docx](https://github.com/andreqbs/e-star/files/444030/Documento.de.caso.de.uso.docx)

**Comment by andreqbs** [comment]
[Modelo Caso de Uso.txt](https://github.com/andreqbs/e-star/files/446164/Modelo.Caso.de.Uso.txt)

**Comment by Elizabetearaujo** [comment]
Segue Casos de uso TCC01
[CSU  Elizabete.pdf](https://github.com/andreqbs/e-star/files/453452/CSU.Elizabete.pdf)

**Comment by marvan123** [comment]
[Realizar Cadastro.pdf](https://github.com/andreqbs/e-star/files/455443/Realizar.Cadastro.pdf)
CSU  só o nome que está realizar cadastro mas ta tudo ai

**Comment by claudiospaiva** [comment]
Segue 
[Casos de Uso_ByCSP.docx](https://github.com/andreqbs/e-star/files/455523/Casos.de.Uso_ByCSP.docx)

**Comment by DerikSoares** [comment]
Casos de uso

**Comment by DerikSoares** [comment]
[Casos de uso.docx](https://github.com/andreqbs/e-star/files/455757/Casos.de.uso.docx)

**Comment by WelltonQ** [comment]
[Casos de Uso.pdf](https://github.com/andreqbs/e-star/files/455808/Casos.de.Uso.pdf)

Casos de uso!

**Comment by matheussiq** [comment]
Casos de Uso
[Casos de Uso.pdf](https://github.com/andreqbs/e-star/files/455857/Casos.de.Uso.pdf)

**Comment by domingosliraneto** [comment]
Segue me Anexo o Modelo de Caso de Uso
[Modelo De Caso de Uso2.0.pdf](https://github.com/andreqbs/e-star/files/455858/Modelo.De.Caso.de.Uso2.0.pdf)
