### ISSUE TITLE
Diagrama de Casos de Uso

### ISSUE THREAD

**Issue by andreqbs** [andreqbs/e-star#3]

**Comment by domingosliraneto** [comment]
Conforme solicitado, segue em anexo o Diagrama de Casos de Uso.

Att,
Domingos L.A. Neto
Setor de Desenvolvimento, Back-End.

[Diagrama de Casos de Uso 1.0.pdf](https://github.com/andreqbs/e-star/files/441533/Diagrama.de.Casos.de.Uso.1.0.pdf)

**Comment by claudiospaiva** [comment]
Segue o diagrama de casos de uso.
![diagrama_bycsp_2](https://cloud.githubusercontent.com/assets/12423483/18071783/db659ac2-6e2e-11e6-87ec-7cb4e6392914.jpg)

**Comment by andreqbs** [comment]
[UseCase Diagram.zip](https://github.com/andreqbs/e-star/files/446162/UseCase.Diagram.zip)

**Comment by Elizabetearaujo** [comment]
Segue diagrama de CSU
[UseCase Diagram Elizabete.zip](https://github.com/andreqbs/e-star/files/453455/UseCase.Diagram.Elizabete.zip)

**Comment by WelltonQ** [comment]
Diagrama de CSU

[UseCase Diagram.zip](https://github.com/andreqbs/e-star/files/455816/UseCase.Diagram.zip)
